name: Lint-Minimal

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  lint:
    runs-on: archlinux-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Clippy lint
        run: cargo clippy -- -D warnings
      - name: Check formatting
        run: cargo fmt --all -- --check
