name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Build
        run: cargo build --release
      - name: Run tests
        run: cargo test --all-features
      - name: Package binary
        run: |
          mkdir -p dist
          cp target/release/heist dist/ || cp target\release\heist.exe dist/ || true
          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            7z a heist-${{ github.ref_name }}-windows-x86_64.zip dist/heist.exe
          elif [ "${{ matrix.os }}" = "macos-latest" ]; then
            tar -czvf heist-${{ github.ref_name }}-macos-x86_64.tar.gz -C dist heist
          else
            tar -czvf heist-${{ github.ref_name }}-linux-x86_64.tar.gz -C dist heist
          fi
      - name: Generate checksums
        run: |
          sha256sum heist-* > checksums.txt || shasum -a 256 heist-* > checksums.txt
      - name: Generate changelog
        id: changelog
        uses: heinrichreimer/github-changelog-generator-action@v2.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: ${{ steps.changelog.outputs.changelog }}
          files: |
            heist-${{ github.ref_name }}-linux-x86_64.tar.gz
            heist-${{ github.ref_name }}-macos-x86_64.tar.gz
            heist-${{ github.ref_name }}-windows-x86_64.zip
            checksums.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
